---
apiVersion: v1
kind: Secret
metadata:
  name: insights-postgres
type: Opaque
stringData:
  database-user: insights
  database-password: insights
  database-name: insights
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: insights-postgres
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: insights-postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      app: insights-postgres
  template:
    metadata:
      labels:
        app: insights-postgres
    spec:
      containers:
      - name: postgres
        image: registry.redhat.io/rhel9/postgresql-16
        ports:
        - containerPort: 5432
          name: postgres
          protocol: TCP
        env:
        - name: POSTGRESQL_USER
          valueFrom:
            secretKeyRef:
              name: insights-postgres
              key: database-user
        - name: POSTGRESQL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: insights-postgres
              key: database-password
        - name: POSTGRESQL_DATABASE
          valueFrom:
            secretKeyRef:
              name: insights-postgres
              key: database-name
        volumeMounts:
        - name: data
          mountPath: /var/lib/pgsql/data
      volumes:
      - name: data
        persistentVolumeClaim:
          claimName: insights-postgres
---
apiVersion: v1
kind: Service
metadata:
  name: insights-postgres
spec:
  selector:
    app: insights-postgres
  ports:
  - protocol: TCP
    port: 5432
    targetPort: 5432
    name: postgres
  type: ClusterIP
