apiVersion: v1
kind: ServiceAccount
metadata:
  name: insights-on-prem
  namespace: insights-on-prem-poc
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: insights-on-prem-metrics-reader
rules:
- apiGroups:
  - ""
  resources:
  - namespaces
  verbs:
  - get
- apiGroups:
  - cluster.open-cluster-management.io
  resources:
  - managedclusters
  verbs:
  - metrics/*
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: insights-on-prem-metrics-reader
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: insights-on-prem-metrics-reader
subjects:
  - kind: ServiceAccount
    name: insights-on-prem
    namespace: insights-on-prem-poc
