apiVersion: v1
kind: Namespace
metadata:
  name: insights-on-prem
---
# Allows the Placement in this namespace to select clusters from the default ManagedClusterSet.
apiVersion: cluster.open-cluster-management.io/v1beta2
kind: ManagedClusterSetBinding
metadata:
  name: global
  namespace: insights-on-prem
spec:
  clusterSet: global
