apiVersion: v1
kind: Namespace
metadata:
  name: open-cluster-management-insights
  labels:
    app: insights-on-prem
---
apiVersion: cluster.open-cluster-management.io/v1beta2
kind: ManagedClusterSetBinding
metadata:
  name: default
  namespace: open-cluster-management-insights
spec:
  clusterSet: default
